spring:
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:juniq;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
